### ISSUE TITLE
Dataset not found and CUDA libraries version error

### ISSUE THREAD

**Issue by hhhhh-dei** [thanh-guong/master-thesis#7]
Executing:  18%|█▊        | 7/39 [00:05<00:16,  1.99cell/s]2024-12-23 16:14:01.547662: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-12-23 16:14:01.547820: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Executing:  28%|██▊       | 11/39 [00:17<00:45,  1.63s/cell]
Traceback (most recent call last):
  File "D:\Anaconda\envs\master\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Anaconda\envs\master\lib\site-packages\papermill\iorw.py", line 544, in local_file_io_cwd
    yield
  File "D:\Anaconda\envs\master\lib\site-packages\papermill\execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "D:\Anaconda\envs\master\lib\site-packages\papermill\execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [5]":
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[5], line 1
----> 1 dataset_df = datasetlib.load_dataset_dataframe(DATASET_2016_10a_FILENAME)
File D:\AAAdybrqs\master-thesis-main\datasetlib.py:54, in load_dataset_dataframe(dataset_filename, dataset)
     42 """
     43     Opens the dataset file, and returns it as a pandas DataFrame.
     44 
   (...)
     50         pandas DataFrame containing dataset.
     51 """
     53 if dataset is None:
---> 54     dataset = load_dataset(dataset_filename)
     56 dataset_dataframe = pd.DataFrame(data=dataset)
     58 # pandas aesthetics
File D:\AAAdybrqs\master-thesis-main\datasetlib.py:22, in load_dataset(dataset_filename)
     10 """
     11     Opens the dataset file, and returns it as a list of tuples.
     12 
   (...)
     17         List of tuples (signal, modulation, snr) with data from dataset.
     18 """
     20 dataset = []
---> 22 with (open(dataset_filename, "rb")) as dataset_file:
     23     data = dataset_file.read()
     24     data_dict = pickle.loads(data, encoding='bytes')  # unpickle data
FileNotFoundError: [Errno 2] No such file or directory: '../data/RML2016.10a_dict.pkl'

**Comment by thanh-guong** [comment]
Hi there,
thank you for contacting me.

It seems you are faceing two different errors:

1. Something about CUDA is missing
2. The software can't find the dataset _RML2016.10a_dict.pkl_ in directory _data_

My answers:

1. Did you install CUDA components as written [here](https://github.com/thanh-guong/master-thesis?tab=readme-ov-file#cuda)?
2. Did you download the dataset, and placed it in the _data_ directory as written [here](https://github.com/thanh-guong/master-thesis/tree/main?tab=readme-ov-file#dataset)?

**Comment by hhhhh-dei** [comment]
Hi, I'm sorry this still hasn't been resolved. I checked your answer and I have installed CUDA and downloaded the dataset and put it in the date.I would like to ask if what I did is correct. I created a date folder in the downloaded file directory and then put the dataset under date.Which file do I need to run to do this?

**Comment by hhhhh-dei** [comment]
Hi, thank you very much for your answer. I have successfully solved the dataset problem, but a new problem has arisen. I have installed the CUDA component, but it still reports an error.
Executing:  18%|█▊        | 7/39 [00:06<00:19,  1.68cell/s]2024-12-24 17:27:03.412631: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-12-24 17:27:03.412876: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Executing:  59%|█████▉    | 23/39 [00:42<00:23,  1.44s/cell]2024-12-24 17:27:39.019155: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library nvcuda.dll
2024-12-24 17:27:40.598415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 4060 Laptop GPU computeCapability: 8.9
coreClock: 1.89GHz coreCount: 24 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 238.45GiB/s
2024-12-24 17:27:40.599721: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-12-24 17:27:40.600668: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2024-12-24 17:27:40.601574: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2024-12-24 17:27:40.602473: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2024-12-24 17:27:40.603883: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library curand64_10.dll
2024-12-24 17:27:40.672324: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusolver64_11.dll
2024-12-24 17:27:40.673543: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2024-12-24 17:27:40.674680: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2024-12-24 17:27:40.674771: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-12-24 17:27:40.680030: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-24 17:27:40.682026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-12-24 17:27:40.682102: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
Executing:  64%|██████▍   | 25/39 [00:44<00:18,  1.31s/cell]2024-12-24 17:27:41.384701: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
Executing: 100%|██████████| 39/39 [01:53<00:00,  2.90s/cell]
CNN2_DFT.ipynb
Executing:  11%|█         | 4/37 [00:07<00:47,  1.43s/cell]2024-12-24 17:28:57.642553: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-12-24 17:28:57.642647: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Executing:  57%|█████▋    | 21/37 [00:28<00:20,  1.26s/cell]2024-12-24 17:29:18.561353: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library nvcuda.dll
2024-12-24 17:29:20.107600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 4060 Laptop GPU computeCapability: 8.9
coreClock: 1.89GHz coreCount: 24 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 238.45GiB/s
2024-12-24 17:29:20.118549: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-12-24 17:29:20.129109: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2024-12-24 17:29:20.137667: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2024-12-24 17:29:20.148818: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2024-12-24 17:29:20.159749: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library curand64_10.dll
2024-12-24 17:29:20.588113: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusolver64_11.dll
2024-12-24 17:29:20.598009: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2024-12-24 17:29:20.603866: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2024-12-24 17:29:20.605064: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-12-24 17:29:20.608270: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-24 17:29:20.614610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-12-24 17:29:20.616776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]

**Comment by hhhhh-dei** [comment]
I would like to ask what versions of cuda and cuDNN you installed

**Comment by thanh-guong** [comment]
Hi there, I'm happy you solved the dataset error!

Thank you for giving details, I ask you to do a clean install of the software versions below:

- CUDA Toolkit: 11.2
- cuDNN: 8.1

Please let me know

**Comment by hhhhh-dei** [comment]
Thanks for your detailed reply!I have solved the problem about CUDA!
I'm sorry, but I still want to ask you the specific steps. If I want to get the result, which file should I run and what are the steps to run it.

**Comment by thanh-guong** [comment]
Thanks for your feedback, happy that it worked!

Please open another issue for the instructions, I'll answer there.

Thank you,
Best regards
